# Generated by Django 3.0.1 on 2020-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0002_locality_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='locality_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
