# Generated by Django 3.0.1 on 2020-01-09 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0005_auto_20200109_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=20)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locality.Locality')),
            ],
        ),
    ]
